### ISSUE TITLE
Newest pylint (2.15.4) has intriduced some new rules.

### ISSUE THREAD

**Issue by francescalb** [emmo-repo/EMMOntoPy#534]
See error when running pre-commit run --all-files

**Comment by CasperWA** [comment]
I think we should consider "pinning"/allowing a more restrictive range of pylint versions (as discussed offline). So instead of having the dependency be `pylint~=2.15`, which is equal to `pylint>=2.15,<3`, it should probably only allow a specific minor version at a time, i.e.: `pylint~=2.15.0` or similar, which is equal to `pylint>=2.15.0,<2.16`.

An alternative is to use `==` and stick to a single specific version at any given time. While this, honestly, might be the best solution for this package, it also gives rise to certain issues/annoyances:
- Many more `pylint` package dependabot PRs.
- A possibility to lose out on automatically published hotfixes.

**Comment by francescalb** [comment]
Hmm... I don't think that we have run into a situation where it is impossible to keep up with pylint restrictions yet. I'd rather keep it as is and try to stay on top of new released suggestions for improved code (but one can also decide on a team-level to disregard certain rules, altough I prefer to keep this to an absolute minimum).
